In [1]:
from taxcalc import *

In [2]:
# Original Weights and PUF
recs = Records('puf_current.csv', weights='puf_weights_current.csv', adjust_ratios='puf_ratios_current.csv')
pol = Policy()
calc = Calculator(records=recs, policy=pol)

You loaded data for 2009.
Calculator instantiation automatically extrapolated your data to 2013.

In [3]:
# New weights and PUF
recs_new = Records()
pol_new = Policy()
calc_new = Calculator(records=recs_new, policy=pol_new)

You loaded data for 2009.
Your data include the following unused variables that will be ignored:
  vb
  medicarex
  gender_spouse
  ftpt_spouse
  snap_participations
  vb_participations
  vb_participationp
  ssip
  ftpt_head
  snap
  gender_head
  snapp
  snaps
  n1821
  hga_head
  ssi_participationp
  ssi_participations
  ssi
  nu18
  snap_participationp
  n21
  medicarexs
  medicarexp
  hga_spouse
  vbs
  vbp
Calculator instantiation automatically extrapolated your data to 2013.

In [4]:
calc.advance_to_year(2016)
calc.calc_all()
calc_new.advance_to_year(2016)
calc_new.calc_all()

In [5]:
# CBO revenue projections
cbo = pd.read_csv('cbo_projections2016.csv', index_col=0)

In [6]:
new_cols = list()
for i in range(2016, 2027):
    new_cols.append(i)
cbo.columns = new_cols

# Diagnostic Tables

## Current Tax Calc

In [7]:
current = utils.multiyear_diagnostic_table(calc, 11)
current

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
Returns (#m),167.6,170.4,173.2,175.8,177.8,180.1,182.4,184.6,186.8,188.9,191.1
AGI ($b),"11,019.8","11,440.8","11,871.1","12,276.4","12,716.1","13,216.4","13,760.1","14,339.6","14,948.2","15,587.9","16,258.3"
Itemizers (#m),43.9,44.8,45.5,46.1,46.8,47.4,47.9,48.5,49.1,49.7,50.3
Itemized Deduction ($b),"1,216.8","1,268.7","1,328.8","1,387.9","1,452.8","1,521.3","1,593.6","1,670.0","1,747.4","1,827.6","1,911.0"
Standard Deduction Filers (#m),110.2,111.9,113.6,115.2,116.3,117.7,119.1,120.3,121.6,123.0,124.3
Standard Deduction ($b),974.0,996.2,"1,034.2","1,073.2","1,110.4","1,150.7","1,192.6","1,234.1","1,277.6","1,322.9","1,370.0"
Personal Exemption ($b),"1,164.0","1,175.7","1,214.4","1,254.3","1,295.0","1,336.5","1,378.9","1,423.2","1,468.2","1,514.9","1,562.9"
Taxable Income ($b),"8,154.1","8,492.6","8,802.4","9,086.9","9,391.8","9,759.9","10,169.2","10,603.7","11,066.9","11,556.4","12,069.6"
Regular Tax ($b),"1,883.6","1,956.6","2,017.9","2,074.0","2,136.6","2,217.9","2,311.8","2,411.4","2,518.8","2,633.4","2,753.6"
AMT Income ($b),"10,425.7","10,822.0","11,222.6","11,599.4","12,005.1","12,471.6","12,980.1","13,519.8","14,089.3","14,687.9","15,315.5"
AMT Liability ($b),42.7,44.9,47.2,49.6,51.5,54.3,57.6,60.3,63.3,66.2,69.2
AMT Filers (#m),5.3,5.6,5.7,5.8,5.9,6.1,6.2,6.4,6.5,6.7,6.9
Tax before Credits ($b),"1,748.6","1,822.0","1,884.2","1,942.4","2,003.6","2,082.6","2,173.6","2,269.3","2,372.1","2,481.3","2,595.9"
Refundable Credits ($b),96.8,96.5,98.3,100.4,102.1,104.1,105.8,107.7,109.5,111.3,113.2
Nonrefundable Credits ($b),73.8,74.6,75.1,75.5,76.1,76.7,77.8,79.2,80.8,82.5,84.4
Reform Surtaxes ($b),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Ind Income Tax ($b),"1,625.9","1,699.7","1,760.3","1,816.5","1,876.8","1,955.1","2,045.4","2,140.1","2,242.1","2,350.4","2,464.1"
Payroll Taxes ($b),"1,039.7","1,093.5","1,139.2","1,181.1","1,224.9","1,271.6","1,321.1","1,374.0","1,428.9","1,485.8","1,545.1"
Combined Liability ($b),"2,665.5","2,793.2","2,899.5","2,997.7","3,101.7","3,226.7","3,366.5","3,514.1","3,671.0","3,836.2","4,009.2"
With Income Tax <= 0 (#m),71.1,71.2,72.1,73.2,73.6,74.4,75.1,75.5,76.0,76.4,76.8
With Combined Tax <= 0 (#m),41.4,41.7,42.5,43.4,43.7,44.3,45.0,45.3,45.8,46.2,46.6

## New TaxCalc

In [8]:
new = utils.multiyear_diagnostic_table(calc_new, 11)
new

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
Returns (#m),168.0,170.9,173.7,176.3,178.5,180.9,183.1,185.3,187.6,189.9,192.1
AGI ($b),"11,021.1","11,444.5","11,875.9","12,280.7","12,719.7","13,220.5","13,763.0","14,342.6","14,951.9","15,590.5","16,259.2"
Itemizers (#m),43.8,44.6,45.3,45.9,46.5,47.1,47.7,48.3,48.9,49.5,50.0
Itemized Deduction ($b),"1,218.2","1,270.5","1,330.5","1,388.6","1,452.5","1,522.1","1,594.2","1,668.4","1,746.5","1,825.2","1,908.2"
Standard Deduction Filers (#m),110.6,112.4,114.1,115.7,117.0,118.3,119.7,120.9,122.3,123.6,125.0
Standard Deduction ($b),979.4,"1,002.2","1,040.1","1,079.1","1,117.5","1,157.0","1,198.1","1,239.8","1,283.0","1,328.2","1,374.9"
Personal Exemption ($b),"1,164.0","1,176.0","1,214.6","1,254.3","1,294.6","1,335.8","1,378.6","1,422.4","1,467.3","1,513.8","1,561.7"
Taxable Income ($b),"8,154.4","8,496.6","8,808.8","9,091.6","9,402.8","9,771.1","10,175.4","10,615.6","11,080.6","11,571.6","12,085.5"
Regular Tax ($b),"1,879.4","1,955.4","2,020.2","2,076.8","2,142.2","2,223.8","2,315.5","2,417.4","2,525.8","2,641.5","2,762.6"
AMT Income ($b),"10,427.6","10,826.0","11,227.1","11,603.1","12,010.1","12,476.6","12,983.0","13,525.4","14,094.8","14,694.0","15,320.3"
AMT Liability ($b),45.1,47.5,49.7,51.9,54.4,57.3,60.2,63.3,66.6,69.7,72.9
AMT Filers (#m),6.0,6.3,6.4,6.5,6.6,6.7,6.9,7.0,7.2,7.4,7.6
Tax before Credits ($b),"1,747.8","1,823.9","1,888.9","1,947.0","2,011.3","2,090.7","2,179.3","2,277.3","2,381.3","2,491.7","2,607.2"
Refundable Credits ($b),97.1,96.7,98.4,100.4,102.3,104.1,105.8,107.6,109.2,110.9,112.7
Nonrefundable Credits ($b),73.3,74.1,74.7,75.1,75.5,76.2,77.2,78.6,80.1,81.8,83.7
Reform Surtaxes ($b),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Ind Income Tax ($b),"1,624.9","1,701.5","1,765.3","1,821.7","1,885.1","1,963.9","2,051.8","2,149.1","2,252.7","2,362.4","2,477.2"
Payroll Taxes ($b),"1,028.1","1,081.4","1,126.8","1,169.0","1,211.3","1,257.6","1,307.4","1,359.4","1,413.5","1,469.9","1,528.6"
Combined Liability ($b),"2,653.0","2,782.9","2,892.1","2,990.6","3,096.4","3,221.5","3,359.2","3,508.5","3,666.2","3,832.4","4,005.8"
With Income Tax <= 0 (#m),71.5,71.9,72.9,73.9,74.6,75.3,75.9,76.4,76.8,77.3,77.7
With Combined Tax <= 0 (#m),41.9,42.3,43.1,43.8,44.5,45.2,45.7,46.1,46.6,47.1,47.5

## New - Current

In [9]:
new - current

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
Returns (#m),0.4,0.5,0.5,0.5,0.7,0.8,0.6,0.8,0.8,0.9,0.9
AGI ($b),1.3,3.7,4.8,4.3,3.6,4.1,2.9,3.0,3.7,2.5,0.8
Itemizers (#m),-0.1,-0.2,-0.2,-0.2,-0.3,-0.3,-0.2,-0.3,-0.2,-0.2,-0.3
Itemized Deduction ($b),1.5,1.8,1.7,0.7,-0.2,0.8,0.6,-1.6,-0.9,-2.4,-2.9
Standard Deduction Filers (#m),0.4,0.5,0.5,0.5,0.7,0.7,0.5,0.6,0.6,0.6,0.6
Standard Deduction ($b),5.4,6.0,5.9,5.9,7.1,6.3,5.4,5.7,5.4,5.3,4.9
Personal Exemption ($b),-0.0,0.3,0.2,0.1,-0.3,-0.7,-0.4,-0.8,-0.9,-1.1,-1.2
Taxable Income ($b),0.3,4.0,6.4,4.7,11.0,11.3,6.2,11.9,13.7,15.2,15.8
Regular Tax ($b),-4.3,-1.3,2.3,2.7,5.6,5.9,3.7,6.0,7.0,8.1,9.0
AMT Income ($b),1.9,4.1,4.5,3.7,5.0,5.0,3.0,5.6,5.5,6.1,4.8
AMT Liability ($b),2.4,2.6,2.5,2.3,2.9,3.0,2.6,3.1,3.3,3.5,3.7
AMT Filers (#m),0.6,0.7,0.7,0.6,0.7,0.7,0.6,0.7,0.7,0.7,0.7
Tax before Credits ($b),-0.8,1.9,4.7,4.6,7.7,8.1,5.7,8.0,9.2,10.4,11.3
Refundable Credits ($b),0.3,0.3,0.1,-0.0,0.2,0.0,0.0,-0.2,-0.3,-0.4,-0.5
Nonrefundable Credits ($b),-0.5,-0.5,-0.4,-0.4,-0.6,-0.5,-0.6,-0.6,-0.7,-0.7,-0.7
Reform Surtaxes ($b),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Ind Income Tax ($b),-0.9,1.8,5.0,5.1,8.3,8.8,6.4,9.0,10.5,12.0,13.0
Payroll Taxes ($b),-11.6,-12.1,-12.4,-12.2,-13.6,-13.9,-13.7,-14.6,-15.3,-15.8,-16.5
Combined Liability ($b),-12.5,-10.3,-7.4,-7.0,-5.3,-5.1,-7.3,-5.6,-4.8,-3.8,-3.5
With Income Tax <= 0 (#m),0.4,0.7,0.8,0.7,1.0,1.0,0.7,0.9,0.9,0.9,0.9
With Combined Tax <= 0 (#m),0.4,0.6,0.6,0.5,0.8,0.9,0.7,0.8,0.8,0.9,0.9

## CBO

In [10]:
cbo

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
Ind Income Tax ($b),"1,553.4","1,666.8","1,780.2","1,876.7","1,968.5","2,069.4","2,171.9","2,276.7","2,390.4","2,511.0","2,636.7"
Payroll Taxes ($b),"1,114.1","1,149.3","1,188.0","1,227.5","1,266.9","1,314.9","1,363.7","1,413.9","1,465.1","1,521.5","1,578.9"
Combined Liability ($b),"2,667.5","2,816.2","2,968.1","3,104.2","3,235.4","3,384.4","3,535.6","3,690.7","3,855.5","4,032.5","4,215.5"

## New - CBO

In [11]:
new_dif = new[16:19] - cbo
new_dif

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
Ind Income Tax ($b),71.5,34.7,-14.9,-55.0,-83.4,-105.5,-120.1,-127.7,-137.7,-148.6,-159.5
Payroll Taxes ($b),-86.0,-67.9,-61.2,-58.6,-55.6,-57.3,-56.3,-54.5,-51.6,-51.6,-50.2
Combined Liability ($b),-14.5,-33.2,-76.1,-113.6,-139.0,-162.8,-176.4,-182.1,-189.3,-200.2,-209.7

## Current - CBO

In [12]:
current_dif = current[16:19] - cbo
current_dif

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
Ind Income Tax ($b),72.5,32.9,-19.8,-60.1,-91.7,-114.3,-126.5,-136.6,-148.2,-160.6,-172.5
Payroll Taxes ($b),-74.4,-55.8,-48.8,-46.4,-42.0,-43.4,-42.6,-39.9,-36.3,-35.7,-33.8
Combined Liability ($b),-1.9,-22.9,-68.6,-106.6,-133.7,-157.7,-169.1,-176.5,-184.5,-196.3,-206.3

In [13]:
new_dif - current_dif

,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
Ind Income Tax ($b),-0.9,1.8,5.0,5.1,8.3,8.8,6.4,9.0,10.5,12.0,13.0
Payroll Taxes ($b),-11.6,-12.1,-12.4,-12.2,-13.6,-13.9,-13.7,-14.6,-15.3,-15.8,-16.5
Combined Liability ($b),-12.5,-10.3,-7.4,-7.0,-5.3,-5.1,-7.3,-5.6,-4.8,-3.8,-3.5

In [14]:
(calc.records.e00200 * calc.records.s006).sum() - (calc_new.records.e00200 * calc_new.records.s006).sum()

26391052.77734375